name: Lint

on:
  push:
    branches:
    - master
  pull_request:

jobs:
  eslint:
    name: eslint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: install node v12
      uses: actions/setup-node@v1
      with:
        node-version: 12
    - name: yarn
      run: yarn --ignore-scripts
    - name: eslint
      uses: icrawl/action-eslint@v1
      with:
        job-name: eslint